TRUNCATE TBL_ARTEFATO CASCADE;
TRUNCATE TBL_ATRIBUTO CASCADE;
TRUNCATE TBL_RELACIONAMENTO_ARTEFATO CASCADE;
TRUNCATE TBL_SISTEMA CASCADE;
TRUNCATE TBL_TIPO CASCADE;


INSERT INTO public.tbl_tipo(
	co_tabela, co_tipo, de_tipo, ic_pesquisavel, ic_exibir_atributo, ic_exibir_grafo, co_cor, co_cor_borda, nu_largura_borda)
	VALUES 
('ATRIBUTO','VARIAVEL','Variável',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','TIPO','Tipo',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','DESCRICAO','Descrição',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','ENLACE','Enlace',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','POSICAO','Posição',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','DECLARACAO-COMPLETA','Declaração Completa',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','VALOR-PADRAO','Valor Padrão',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JAVA-PACKAGE','(JAVA) Package',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JAVA-CANONICAL-NAME','(JAVA) Canonical Name',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JAVA-IMPORT','(JAVA) Import',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','RECORDING-MODE','(COBOL) Recording Mode',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','DATA-RECORD','(COBOL) Data Record',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','BLOCK-CONTAINS','(COBOL) Block Contains',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','RECORD-CONTAINS','(COBOL) Record Contains',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','OPTIONAL','Optional',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-VARIAVEL-EXTERNAL','(COBOL) Variável External',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-VARIAVEL-BINARY','(COBOL) Variável Binay',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-REDEFINE','(COBOL) Variável Redefine',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-HIERARQUIA-VARIAVEL','(COBOL) Variável Hierarquia',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-FILE-NAME','(COBOL) File Name',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-DDNAME','(COBOL) DDName',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-ORGANIZATION','(COBOL) Organization',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-ACCESS-MODE','(COBOL) Access Mode',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-RECORD-KEY','(COBOL) Record Key',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-ALTERNATE-RECORD-KEY','(COBOL) Alternate Record Key',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-READ','(COBOL) FD Read',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-WRITE','(COBOL) FD Write',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-REWRITE','(COBOL) FD Rewrite',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','COBOL-DELETE','(COBOL) FD Delete',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-INPUT','(Control-M) Input',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-OUTPUT','(Control-M) Output',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-OUTPUT-SINAL','(Control-M) Output Sinal',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-OWNER','(Control-M) Owner',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-TASKTIP','(Control-M) Tasktip',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-GROUP-NAME','(Control-M) Group Name',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-DOC-MEM','(Control-M) DocMem',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-OVERLIB','(Control-M) Overlib',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-DOCLIB','(Control-M) Doclib',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CONTROLM-MEMNAME','(Control-M) Memname',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JCL-DELETE-ON-JCL','(JCL) Delete',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JCL-DISP-STATUS','(JCL) Disp',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JCL-DISP-NORMAL-DISPOSITION','(JCL) Normal Disposition',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JCL-DISP-ABNORMAL-DISPOSITION','(JCL) Abnormal Disposition',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JCL-TIPO-EXEC','(JCL) Tipo Exec',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','JCL-NOME-PGM-PROC','(JCL) Nome PGM Exec',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-LABEL','(CICS) Label',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-ENDDATA','(CICS) EndData',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-ERROR','(CICS) Error',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-QNAME','(CICS) Qname',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-NUMITEMS','(CICS) NumItems',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-ITEM','(CICS) Item',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-ASKTIME','(CICS) Asktime',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-INTO','(CICS) Into',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-ABSTIME','(CICS) Abstime',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-COMMAREA','(CICS) Commarea',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-PROGRAM','(CICS) Programa',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-USER-ID','(CICS) UserId',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-SYSTEM-ID','(CICS) SystemId',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-R-TRANSACTION-ID','(CICS) R Transation ID',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-R-TERMINAL-ID','(CICS) R Terminal ID',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-QUEUE','(CICS) Queue',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-TIME','(CICS) Time',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-LENGTH','(CICS) Length',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-REQ-ID','(CICS) Req ID',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-TERMINAL-ID','(CICS) Terminal ID',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-FROM','(CICS) From',false,true,false,'#000000','#000000', 1),
('ATRIBUTO','CICS-TRANSACTION-ID','(CICS) Transaction ID',false,true,false,'#000000','#000000', 1),
('ARTEFATO','COPYBOOK','Copybook',true,false,true,'#fbc02d','#fbc02d', 1),
('ARTEFATO','COPYBOOK-VARIAVEL','Copybook Variável',false,false,false,'#FFFFFF','#fbc02d', 1),
('ARTEFATO','PROGRAMA-COBOL','Programa Cobol',true,false,true,'#64b5f6','#64b5f6', 1),
('ARTEFATO','PROGRAMA-COBOL-PARAGRAFO','Programa Cobol Parágrafo',false,false,false,'#FFFFFF','#64b5f6', 1),
('ARTEFATO','CICS-TRANSACTION','CICS Transaction',false,true,true,'#004f8f','#004f8f', 1),
('ARTEFATO','DDNAME','DDName',true,false,true,'#FFFFFF','darkkhaki', 1),
('ARTEFATO','FILE-DESCRIPTION','File Description',true,false,true,'#000000','#000000', 1),
('ARTEFATO','TABELA','Tabela',true,false,true,'green','green', 1),
('ARTEFATO','TABELA-CAMPO','Tabela Campo',false,true,true,'#FFFFFF','green', 1),
('ARTEFATO','UTILITARIO','Utilitário',false,false,true,'steelblue','steelblue', 1),
('ARTEFATO','DECLARACAO-SQL','Declaração SQL',false,false,true,'#000000','#000000', 1),
('ARTEFATO','DESCONHECIDO','Desconhecido',true,false,true,'#000000','#000000', 1),
('ARTEFATO','JCL','JCL',true,false,true,'#e57373','#e57373', 1),
('ARTEFATO','JCL-STEP','JCL Step',true,false,true,'#FFFFFF','#e57373', 1),
('ARTEFATO','DSN','DSN',true,false,true,'darkkhaki','darkkhaki', 1),
('ATRIBUTO','PROCESSO-CRITICO','Processo Crítico',true,true,true,'orange','orange', 1),
('ATRIBUTO','SISTEMA-DESTINO','Sistema Destino',true,true,true,'orange','orange', 1),
('RELACIONAMENTO_ARTEFATO','NORMAL','Normal',false,true,true,'none','#cecece', 0.8),
('RELACIONAMENTO_ARTEFATO','INTERFACE','Interface',false,true,true,'none','#000000', 2),
('RELACIONAMENTO_ARTEFATO','CONTROL-M','Control-M',false,true,true,'none','#e57373', 2),
('RELACIONAMENTO_ARTEFATO','DESATIVADO','Desativado',false,false,false,'none','#e57373', 1);

INSERT INTO public.tbl_artefato(
	no_nome_artefato, no_nome_exibicao, no_nome_interno, co_ambiente, co_sistema, co_tipo_artefato)
	VALUES 
('ADRDSSU','ADRDSSU','ADRDSSU','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('BPXTCAFF','BPXTCAFF','BPXTCAFF','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('CEFEXCIC','CEFEXCIC','CEFEXCIC','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('CONTREG','CONTREG','CONTREG','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('CTMAPI','CTMAPI','CTMAPI','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('DMBATCH','DMBATCH','DMBATCH','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('DSNTIAUL','DSNTIAUL','DSNTIAUL','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('DSNUTILB','DSNUTILB','DSNUTILB','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3OUT','E3OUT','E3OUT','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U130','E3U130','E3U130','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U132','E3U132','E3U132','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U133','E3U133','E3U133','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U134','E3U134','E3U134','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U135','E3U135','E3U135','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U136','E3U136','E3U136','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U500','E3U500','E3U500','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('E3U510','E3U510','E3U510','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('ECEPB609','ECEPB609','ECEPB609','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('ECEPCX1A','ECEPCX1A','ECEPCX1A','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('EPZOS','EPZOS','EPZOS','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('FTP','FTP','FTP','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('HSMPX304','HSMPX304','HSMPX304','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('ICEGENER','ICEGENER','ICEGENER','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('ICEMAN','ICEMAN','ICEMAN','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('ICETOOL','ICETOOL','ICETOOL','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IDCAMS','IDCAMS','IDCAMS','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IEBCOMPR','IEBCOMPR','IEBCOMPR','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IEBCOPY','IEBCOPY','IEBCOPY','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IEBGENER','IEBGENER','IEBGENER','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IEBPTPCH','IEBPTPCH','IEBPTPCH','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IEFBR14','IEFBR14','IEFBR14','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IKJEFT01','IKJEFT01','IKJEFT01','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IKJEFT1A','IKJEFT1A','IKJEFT1A','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('IOACNDPE','IOACNDPE','IOACNDPE','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('ISRSUPC','ISRSUPC','ISRSUPC','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('PKZIP','PKZIP','PKZIP','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('PPRD001','PPRD001','PPRD001','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('PRDVAZTR','PRDVAZTR','PRDVAZTR','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('SORT','SORT','SORT','DESCONHECIDO','DESCONHECIDO','UTILITARIO'),
('SPOOLSTT','SPOOLSTT','SPOOLSTT','DESCONHECIDO','DESCONHECIDO','UTILITARIO');

INSERT INTO public.tbl_sistema(
	co_sistema, de_sistema)
	VALUES 
	('SIPCS', 'SIPCS'),
	('SIFDL', 'SIFDL'),
	('SIEPA', 'SIEPA'),
	('SIACH', 'SIACH'),
	('SIDEC', 'SIDEC'),
	('SISPL', 'SISPL'),
	('SIATC', 'SIATC'),
	('SIGTA', 'SIGTA'),
	('SICAC','SICAC'),
	('SUGAP','SUGAP'),
	('SIGCB','SIGCB'),
	('SICOB','SICOB'),
	('SIGDB','SIGDB'),
	('SICAP','SICAP'),
	('SIACC','SIACC'),
	('SISFIN','SISFIN'),
	('DESCONHECIDO', 'Desconhecido');
