package br.gov.caixa.discovery.core.tipos;

public enum TipoAtributo {
	VARIAVEL("VARIAVEL"), TIPO("TIPO"), DESCRICAO("DESCRICAO"), ENLACE("ENLACE"), POSICAO("POSICAO"),
	DECLARACAO_COMPLETA("DECLARACAO-COMPLETA"), VALOR_PADRAO("VALOR-PADRAO"),

	JAVA_PACKAGE("JAVA-PACKAGE"), JAVA_CANONICAL_NAME("JAVA-CANONICAL-NAME"), JAVA_IMPORT("JAVA-IMPORT"),

	RECORDING_MODE("RECORDING-MODE"), DATA_RECORD("DATA-RECORD"), BLOCK_CONTAINS("BLOCK-CONTAINS"),
	RECORD_CONTAINS("RECORD-CONTAINS"), OPTIONAL("OPTIONAL"),

	COBOL_VARIAVEL_EXTERNAL("COBOL-VARIAVEL-EXTERNAL"), COBOL_VARIAVEL_BINARY("COBOL-VARIAVEL-BINARY"),
	COBOL_REDEFINE("COBOL-REDEFINE"), COBOL_HIERARQUIA_VARIAVEL("COBOL-HIERARQUIA-VARIAVEL"),
	COBOL_FILE_NAME("COBOL-FILE-NAME"), COBOL_DDNAME("COBOL-DDNAME"), COBOL_ORGANIZATION("COBOL-ORGANIZATION"),
	COBOL_ACCESS_MODE("COBOL-ACCESS-MODE"), COBOL_RECORD_KEY("COBOL-RECORD-KEY"),
	COBOL_ALTERNATE_RECORD_KEY("COBOL-ALTERNATE-RECORD-KEY"), COBOL_READ("COBOL-READ"), COBOL_WRITE("COBOL-WRITE"),
	COBOL_REWRITE("COBOL-REWRITE"), COBOL_DELETE("COBOL-DELETE"),

	CONTROLM_MALHA_INPUT("CONTROLM-INPUT"), CONTROLM_MALHA_OUTPUT("CONTROLM-OUTPUT"),
	CONTROLM_MALHA_OUTPUT_SINAL("CONTROLM-OUTPUT-SINAL"), CONTROLM_OWNER("CONTROLM-OWNER"),
	CONTROLM_TASKTIP("CONTROLM-TASKTIP"), CONTROLM_GROUP_NAME("CONTROLM-GROUP-NAME"),
	CONTROLM_DOC_MEM("CONTROLM-DOC-MEM"), CONTROLM_OVERLIB("CONTROLM-OVERLIB"), CONTROLM_DOCLIB("CONTROLM-DOCLIB"),
	CONTROLM_MEMNAME("CONTROLM-MEMNAME"),

	JCL_DELETE_ON_JCL("JCL-DELETE-ON-JCL"), JCL_DISP_STATUS("JCL-DISP-STATUS"),
	JCL_DISP_NORMAL_DISPOSITION("JCL-DISP-NORMAL-DISPOSITION"),
	JCL_DISP_ABNORMAL_DISPOSITION("JCL-DISP-ABNORMAL-DISPOSITION"), JCL_TIPO_EXEC("JCL-TIPO-EXEC"),
	JCL_NOME_PGM_PROC("JCL-NOME-PGM-PROC"),
	//
	CICS_LABEL("CICS-LABEL"),
	CICS_ENDDATA("CICS-ENDDATA"), CICS_ERROR("CICS-ERROR"), CICS_QNAME("CICS-QNAME"), CICS_NUMITEMS("CICS-NUMITEMS"),
	CICS_ITEM("CICS-ITEM"), CICS_ASKTIME("CICS-ASKTIME"), CICS_INTO("CICS-INTO"), CICS_ABSTIME("CICS-ABSTIME"),
	CICS_COMMAREA("CICS-COMMAREA"), CICS_PROGRAM("CICS-PROGRAM"), CICS_USER_ID("CICS-USER-ID"),
	CICS_SYSTEM_ID("CICS-SYSTEM-ID"), CICS_R_TRANSACTION_ID("CICS-R-TRANSACTION-ID"),
	CICS_R_TERMINAL_ID("CICS-R-TERMINAL-ID"), CICS_QUEUE("CICS-QUEUE"), CICS_TIME("CICS-TIME"),
	CICS_LENGTH("CICS-LENGTH"), REQ_ID("CICS-REQ-ID"), CICS_TERMINAL_ID("CICS-TERMINAL-ID"), CICS_FROM("CICS-FROM"),
	CICS_TRANSACTION_ID("CICS-TRANSACTION-ID");

	private String value;

	private TipoAtributo(String value) {
		this.value = value;
	}

	public String get() {
		return this.value;
	}
}
